apiVersion: v1
kind: Namespace
metadata:
  name: #{Release.EnvironmentName}#
---
apiVersion: v1
kind: Secret
metadata:
  name: azuresql
type: Opaque
data:
  connectionstring: #{CosmosDbConnectionString}#
