apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudrouter
  labels:
    app: fraudrouter
spec:
  selector:
    matchLabels:
      app: fraudrouter
  replicas: 3
  template: 
    metadata:
      labels:
        app: fraudrouter
    spec:
      containers:
      - name: fraudrouter
        image: fraudacr.azurecr.io/fraudrouter
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: router-port        
      
