apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudrouter
spec:
  selector:
    matchLabels:
      app: fraudrouter
  replicas: 1 
  template: 
    metadata:
      labels:
        app: fraudrouter
    spec:
      containers:
      - name: fraudrouter
        image: fraudacr.azurecr.io/fraudrouter:5365
        ports:
        - containerPort: 8080
