apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud-node
spec:
  selector:
    matchLabels:
      app: fraud
  replicas: 3
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
      - name: hello
        image: fraudacr.azurecr.io/fraudrouter
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: FraudRouter
