apiVersion: apps/v1
kind: Deployment
metadata:
  name: GatewayConnectorToAnalytics
  labels:
    app: hello-node
spec:
  selector:
    matchLabels:
      app: GatewayConnectorToAnalytics
  replicas: 3
  template:
    metadata:
      labels:
        app: GatewayConnectorToAnalytics
    spec:
      containers:
      - name: hello
        image: fraudacr.azurecr.io/FraudRouter
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: FraudRouter
