apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  labels:
    app: fraudrouter
spec:
  ports:
  - port: 80
    targetPort: router-port
    externalTrafficPolicy: cluster
  selector:
    app: fraudrouter
  type: LoadBalancer
